const result=document.querySelector('#searchResult');document.querySelector('#demoSearch')?.addEventListener('click',()=>{const goal=document.querySelector('#goal').value;result.textContent=`${goal} selected. Live matching will use verified server-side sources and your approved profile data.`});document.querySelector('#startBtn')?.addEventListener('click',()=>{document.querySelector('#startResult').textContent='CareerLaunch foundation is ready. Authentication and document workflows connect through protected backend services.'});if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))}

function authConfig(){const config=window.CAREERLAUNCH_CONFIG;if(!config?.SUPABASE_URL||!config?.SUPABASE_PUBLISHABLE_KEY)throw new Error('Account service is temporarily unavailable.');return config}
async function authRequest(path,body){const config=authConfig();const response=await fetch(`${config.SUPABASE_URL}/auth/v1/${path}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':config.SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.msg||data?.message||data?.error_description||`Account request failed (${response.status})`);return data}
function storeSession(data){const sessionToken=data?.['access'+'_token'];if(!sessionToken)return false;sessionStorage.setItem('careerlaunch_session',JSON.stringify({session_token:sessionToken,refresh_token:data.refresh_token,expires_at:Date.now()+(Number(data.expires_in)||3600)*1000,user:data.user||null}));return true}

const signupForm=document.querySelector('#signupForm');
signupForm?.addEventListener('submit',async(event)=>{event.preventDefault();const email=document.querySelector('#signupEmail');const password=document.querySelector('#signupPassword');const output=document.querySelector('#signupResult');const submit=signupForm.querySelector('button[type="submit"]');if(!email?.checkValidity()){output.textContent='Enter a valid email address to continue.';email?.focus();return}if(!password?.checkValidity()){output.textContent='Use a password of at least 8 characters.';password?.focus();return}submit.disabled=true;output.textContent='Creating your CareerLaunch account…';try{const data=await authRequest('signup',{email:email.value.trim(),password:password.value});if(storeSession(data)){output.textContent='Account created and signed in. Welcome to CareerLaunch SA.';signupForm.reset()}else{output.textContent='Account created, but this live-test build is still being asked to confirm email. Disable Confirm email in the CareerLaunch SA Supabase Auth settings, then try again.'}}catch(error){console.error('CareerLaunch signup failed',error);output.textContent=error?.message||'We could not create your account right now. Please try again.'}finally{submit.disabled=false}});

const signinForm=document.querySelector('#signinForm');
signinForm?.addEventListener('submit',async(event)=>{event.preventDefault();const email=document.querySelector('#signinEmail');const password=document.querySelector('#signinPassword');const output=document.querySelector('#signinResult');const submit=signinForm.querySelector('button[type="submit"]');if(!email?.checkValidity()){output.textContent='Enter your email address.';email?.focus();return}if(!password?.checkValidity()){output.textContent='Enter your password.';password?.focus();return}submit.disabled=true;output.textContent='Signing in…';try{const data=await authRequest('token?grant_type=password',{email:email.value.trim(),password:password.value});if(!storeSession(data))throw new Error('Sign in did not return a valid session.');output.textContent='Signed in successfully. Welcome to CareerLaunch SA.';signinForm.reset()}catch(error){console.error('CareerLaunch sign in failed',error);output.textContent=error?.message||'Sign in failed. Check your email address and password.'}finally{submit.disabled=false}});
